
[functions.analyze-food]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.mp-webhook]
verify_jwt = false

[functions.create-subscription]
enabled = true
verify_jwt = true
import_map = "./functions/create-subscription/deno.json"
entrypoint = "./functions/create-subscription/index.ts"
